### ISSUE TITLE
Choose which productions are shown

### ISSUE THREAD

**Issue by cyler2k19** [jtsage/FS22_ProductionInspector#3]
Hey
would be awesome if you could choose which productions are shown in the hud.
i'm using your mod for over 200 hrs in my current multiplayer savegame on dedicated server and i love it but i already got alot of productions running (with kastors modular bga mod even more productions for just one biogas plant). 
While i really want to know what's happening in my biogas plants and my sugar beet processing plant i don't really want to know whats happening in my two dairy plants or in my sugar factory.
Maybe there is any possibility your mod can scan the active productions and let me choose which one are displayed in the hud?
I already deactivated all inactive productions but i got alot active productions and my screen is full of huds already xD

**Comment by jtsage** [comment]
so, update later today probably (tomorrow at the latest - if your familiar with how github works, my test copy is in the "combo" branch at the moment) - (i'm totally just gonna paste this in your other ticket too, I'm lazy)

Among the new features:
- AnimalInspector is being depreciated and rolled into this one.  Along with SiloInspector (storage silo levels / overall percentage (only shows filltypes that are in use)).  They are all sperate overlays with individual visibility settings and placement (and they stack nice now too if you want to do that)
- Text size selection
- If you add an underscore "_" to the end of a production facility / animal pen / silo name, it will be hidden from the list.  This seemed the easiest way to do this without having to write a whole seperate user interface.  I too don't care about what my BGA is doing :)  I also added a configuration option to limit how many are displayed (alphabetic sort, after all other filters) - not sure how useful it is in real gameplay, but it's helped with some screenshots for sure.

The only downside to the new version is that it's going to clobber your settings file, so be sure to glance at which options you liked which way.  Sorry bout that, but I had to rename some options internally to make it all fit together nicely.

**Comment by cyler2k19** [comment]
That sounds awesome. I don't expected an answer and an update that fast. 
I like that a SiloInspector will be added :) The hide from list option is a great update.
if i find some time today i will test yor combo branch.
For clarification, where do i need to add the underscore to the production?

**Comment by jtsage** [comment]
at the end of the name - go into build / landscape mode, if you click on a building, it will let you rename them - so Something like `My Farm BGA` -> `My Farm BGA_` would hide it.

**Comment by cyler2k19** [comment]
Thanks! I just downloaded the new version and hiding the unwanted productions is super cool.
But i still got one suggestion. In the old production inspector version the text was flush right, when i choose the hud to be right under the clock on the top right side. In the new version its flush left. Could you change it to flush right again?
Old (how i like it)
https://www.directupload.net/file/d/6491/owddxgga_jpg.htm

New
https://www.directupload.net/file/d/6491/hpoytbge_jpg.htm

**Comment by jtsage** [comment]
yeah - so, here is my complaint on the right justify - I don't like how the "headers" work - with the indent on the right - it looks wierd to me.  So, I had to  re-write the output functions anyway, what I am going to attempt to do is right justify all of the data, and center the production point name and see what that looks like.  There was a *ton* of conditional logic based on display mode that I hated - but, yes, this was the one bit that prevented me from tagging this as a release earlier.

As to that BGA - did it come with the map?  and if it did, what map so I can figure out why the "only Owned" isn't filtering it out like it probably should be

Thanks much!

(thinking more, the justification might end up being a setting.  because options are good, right?)

**Comment by cyler2k19** [comment]
I see. sounds good to give it a try with centered production names.
Giving different options of alignments would be an idea. Everyone have different imaginations :D 

Yes the BGA comes with the map. It's the Nordfriesische Marsch Map.
https://www.fedaction-letsplay.de/aktuelle-projekte/ls22-nordfriesische-marsch/
There are two BGAs on the map. I own the BGA Nord which is displayed correctly. I don't own the just BGA named BGA.
With the release version the BGA was filtered out.

**Comment by jtsage** [comment]
Gotcha on the BGA - so I clearly messed something up when I did my re-write.  Cool.  I'll grab a copy of the map and figure it out.

As to the centering - it looked awful.  When i drop in updates later tonight, right side displays will default to right justification, and there is an option on each one now to use the default or force it right or left.

**Comment by jtsage** [comment]
Yeah, turns out when you rename all the options internally, you should do it when you check them too - that is fixed in d16ad79552 - the zip in that branch is what I will test with tonight and tomorrow before I merge it in, take some screenshots, redo the README and release it.  Thanks for the input!!

**Comment by cyler2k19** [comment]
Awesome, tested it today and everything is running fine. 
Thanks for your work, the Inspector Mods are super nice :)
