### ISSUE TITLE
Can the display width be adjusted?

### ISSUE THREAD

**Issue by vitalii2011** [jtsage/FS22_ProductionInspector#5]
![fsScreen_2022_07_29_13_54_56](https://user-images.githubusercontent.com/41552153/181747935-0f60feb2-85b7-48b0-8a8c-2a112614b87d.png)

**Comment by judg393** [comment]
You can set it to hide empty input outputs I believe in the settings that might shorten it :)

**Comment by vitalii2011** [comment]
Everyone knows about "hiding the empty ones", but they will soon be filled.

**Comment by jtsage** [comment]
The width can't be adjusted right now, no - I'd be open to suggestions on how to implement that though - there is a fair amount of math in the placement that assumes all productions will take up the same number of horizontal lines, so line breaks are going to be a little messy.  Just cutting off the line is worse.  

Does it maybe make sense to hide full/nearly full inputs too?  I'm not sure, open to ideas.

**Comment by vitalii2011** [comment]
I can't help you with this, but try asking here:
https://discord.gg/ZWX4DPmb
https://discord.gg/brzzP8xM

**Comment by judg393** [comment]
Hi @jtsage i think if you can make the hide nearly full /full a toggle option that would be cool :) but sorry not a coder to know if I'm asking for a flying pig 

Maybe you could have products shorten mil for milk sil for silage gra for grass? Would likely work in English but no idea on other language

**Comment by jtsage** [comment]
Aye, that is the problem with abbreviations - maintaining them in other languages, and getting something everyone will agree on.

**Comment by judg393** [comment]
Yup I see the dilemma
