### ISSUE TITLE
Production revamp compatible?

### ISSUE THREAD

**Issue by judg393** [jtsage/FS22_ProductionInspector#6]
Hey JT just tried out production revamp from mH and noticed that all my production Chains have disappeared from your monitor :( is this a Conflict or compatibility issue and if so any chances it will get patched?

**Comment by judg393** [comment]
To be honest I say it's product revamp it's the most likely culprit as it changes productions :)

**Comment by jtsage** [comment]
I'll download this and give it a shot, I don't actually know at the moment.

**Comment by judg393** [comment]
Cheers buddy 

I was a little bit heart broken when I realised it had stopped working

**Comment by judg393** [comment]
hi JT

Also noticed im getting Lua errors in the log from the latest PI doesnt seem to be causing any issue although notiving that im CTD rather than main menu when i choose that option (not to bothered by this nor saying its your mods fault just thought you may want to look at it :)
[log.txt](https://github.com/jtsage/FS22_ProductionInspector/files/9229247/log.txt)

**Comment by jtsage** [comment]
yeah, that error is sort of on me - at the very least I should be checking my assumptions in that bit.  gonna work this a bit today and see what I can figure out.

**Comment by jtsage** [comment]
Give this a shot for production revamp - I *think* the only bits I was missing was the addition of the real "storing" output mode - I haven't really used this much yet, so I'll give it some more in-depth testing.  But that log was very, very helpful to find what was missing. https://github.com/jtsage/FS22_ProductionInspector/blob/0811417b858dddf2a0e6dc6a5afb8bfe4707cb73/FS22_ProductionInspector.zip

Edits made in such a way that this should have no effect on base-game functions

**Comment by judg393** [comment]
Gentleman and a scholar its back in business 
and the lua seems to be playing nicely too
