### ISSUE TITLE
ProductionInspector.lua:815: attempt to concatenate a nil value - Incompatibility with Production Revamp mod

### ISSUE THREAD

**Issue by ZincStoat** [jtsage/FS22_ProductionInspector#8]
Hi,
On a couple of maps recently I've had the Productions window fail to show up when I have certain productions running, and my log filling up with the above error. I've finally tracked it down to an issue with running alongside the Production Revamp mod, which adds a fourth state to the Productions OutputMode, "Keep". As this isn't recognised by Production Inspector, the line where it checks and includes g_productionInspector[g_productionInspector.outputModeMap[outputs[5]]] breaks as it finds a 'nil' value.
The solution I've arrived at is to add the following setString after those setting up the other output mode display symbols (choosing the only spare arrow I could think of, but any symbol would do)

ProductionInspector.setStringTextKeep        = "←"

plus this line to the definition for ProductionInspector.outputModeMap

[ProductionPoint.OUTPUT_MODE.KEEP]         = "setStringTextKeep"

Everything now displays as expected and my log's quietened down. Hope you find this useful.

Thanks for an enormously helpful mod.

**Comment by jtsage** [comment]
I beat you to it by a little bit, but this has not been pushed out to the modhub version:

https://github.com/jtsage/FS22_ProductionInspector/commit/0811417b858dddf2a0e6dc6a5afb8bfe4707cb73

Keep in mind, if you do what you did in 
```lua
[ProductionPoint.OUTPUT_MODE.KEEP] = "setStringTextKeep"
```
you'll get an error that ProductionPoint.OUTPUT_MODE.KEEP is nil if you *don't* have revamp loaded, that's why I used the real constant instead of the reference.

**Comment by ZincStoat** [comment]
Ah, rookie mistake, I omitted to check Closed issues before reporting this. Thanks, I'll grab the zip for that instead. I'll most probably have Revamp loaded but just in case.

Thanks again.

**Comment by ZincStoat** [comment]
Upside, it was an interesting exercise in mod debugging.
