### ISSUE TITLE
ProductionInspector.lua:815: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by Skumby** [jtsage/FS22_ProductionInspector#9]
I got the above error after buying a second industrial bakery (Industrial Bakery mod) and turning on all its productions with nothing in its inputs. I have Production Revamp installed. The first industrial bakery worked fine.

Restarting the game does not fix the issue, but does remove the empty boxes. 

Filling the inputs and outputs does not fix the issue. Restarting the game after filling the inputs and outputs does not fix the issue.

![20220912093148_1](https://user-images.githubusercontent.com/48925237/189609794-5f03b883-2e0e-40b3-8b0d-419e5abc9efa.jpg)
![20220912093152_1](https://user-images.githubusercontent.com/48925237/189609829-5f1db889-01cd-49e9-aedf-87641850de8f.jpg)

**Comment by Skumby** [comment]
Update: Cause was completely wrong. Built a new dairy, and filled it. Production Revamp adds new output modes which Inspector does not recognise. Changing the output modes to Distribute/Spawning instead of Storing caused Inspector to start working again.

**Comment by jtsage** [comment]
Give this version a shot - I believe this was fixed, but it has not been "released" or pushed to modhub just yet: https://github.com/jtsage/FS22_ProductionInspector/raw/main/FS22_ProductionInspector.zip

**Comment by Skumby** [comment]
Looks to work fine. Storing productions now get a <- instead of crashing.

**Comment by BullFlag** [comment]
I too saw the same Error  Skumby reported,   LUA line 815 'draw'  with Revamp installed.   I was able to clear the error by switching the option "SHOW OUTPUTS to NO"  

The update V1110 appears to solve it, now Outputs are back ON!   _Appreciate the awesome mod and active support_

**Comment by BullFlag** [comment]
Well, I tried the new GitHub Release V1110 on another Map with latest Revamp.   I had a different error than Skumby reports above.   This time " perform arithmetic on a nil value" Line 999

S22_ProductionInspector/ProductionInspector.lua:999: attempt to perform arithmetic on a nil value
2022-10-31 20:24 Error: Running LUA method 'draw'.

By setting option "SHOW OUTPUTS to NO" I was able to clear the error.   Seems that might be another condition causing the LUA "draw" to throw an error    Can I provide any other details?

**Comment by BullFlag** [comment]
Late responding.   As @judg393 states above 

I tried removing FS22_A_ProductionRevamp and two other mods that required Revamp.  **YES this did clear the buggy behavior**   I no longer needed to set "Show Outputs" option to NO to get fully functional Production Inspector

**Comment by jtsage** [comment]
[FS22_ProductionInspector.zip](https://github.com/jtsage/FS22_ProductionInspector/files/10367469/FS22_ProductionInspector.zip)

This is a testing version, it might fix this.

**Comment by BullFlag** [comment]
Yes that fixed it!  PI now works with Outputs YES, no conflict with FS22_A_ProductionRevamp V1.4 Beta 10 and latest version on GitHub
